# Generated by Django 3.0.14 on 2021-08-10 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique_for_date='date'),
            preserve_default=False,
        ),
    ]
