# Generated by Django 3.0.14 on 2021-08-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='slug',
        ),
    ]
