# Generated by Django 3.0.14 on 2021-08-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_remove_workout_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Run',
        ),
    ]
