# Generated by Django 3.2.6 on 2021-08-14 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0005_auto_20210810_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={},
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterOrderWithRespectTo(
            name='run',
            order_with_respect_to='user',
        ),
    ]
